### PR TITLE
Streamline batching, improved imports and white mode

### LINKED ISSUE #14: Whole tracking is too big for the maximum buffer size
I noticed this fatal error after submitting my last PR. I tried to render `Whole_Brain_Tracking/Subject__whole_brain_wm_tracts_det_comp.trk`. This can be fixed; it just means that we can't batch the whole brain in a single buffer. We'll have to work on a system that supports multiple batches.
```
[2024-08-05T00:51:40Z ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default
thread 'main' panicked at /home/carl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
      note: label = `FiberVertexBuffer`
    Buffer size 866706696 is greater than the maximum buffer size (268435456)
```

### PR DESCRIPTION
**Pull request by carlOSx64**
Fixes #14 

- Replaced `FiberResources` with a vector of `FiberBatch`. Multiple buffers are now created instead of a single one to hold a bunch of streamlines. This code does not account for the maximum buffer size and the size of streamlines. This could cause allocation errors if the device can't support the size of a batch. I'm not sure this will occur often in practice, but I added the `batch_size` parameter just in case.
- Added support for a white background using the `white` parameter.
- Cleaned some imports to comply with the preferred import style.

### CODE REVIEW

File: src/graphics/resources/bind/group.rs [hunk 1]
```diff
@@ -18,21 +20,23 @@ pub fn transform(ctx: &Context) -> BindGroup {
...
-
-    device.create_sampler(&wgpu::SamplerDescriptor {
-        address_mode_u: AddressMode::ClampToEdge,
-        address_mode_v: AddressMode::ClampToEdge,
+fn create_sampler(client: &Client) -> wgpu::Sampler {
+    let border_color = if client.white_mode {
+        SamplerBorderColor::OpaqueWhite
+    } else {
+        SamplerBorderColor::OpaqueBlack
+    };
```
Comment (nilgoyette) [inline src/graphics/resources/bind/group.rs:28]: Thanks for this. However, it's more complex than that. At least, it was in our Python version. The problem is that the data is seldom clean. The background is not always equal to zero. Most of the time, it's near 0, but this fact doesn't help us much. I didn't test this PR, but iiuc, this will create a black-ish square inside a white background. What most people want is only the brain, not the whole square.

After some research, we decided that a brain mask is required if the user requires a white background. When he provides it, we set all non-masked voxels to 255 (white) + we ask vtk for a white background: this gives us a white background.

File: src/graphics/pipeline.rs [hunk 2]
```diff
@@ -17,11 +20,11 @@ pub struct Pipelines {
 
 impl Pipelines {
     pub fn new(res: &Resources, client: &Client) -> Self {
-        let streamline = res
-            .fibers
-            .as_ref()
-            .map(|_| create_pipeline(state::streamline(), res, client));
-
+        let streamline = if !res.fibers.is_empty() {
```
Comment (nilgoyette) [inline src/graphics/pipeline.rs]: Hahaha, all this thinking to revert back to a if else none :D 

If you liked the previous style, you can keep it with a

    (!res.fibers.is_empty()).then(...)

File: src/graphics/resources/fibers.rs [hunk 3]
```diff
@@ -25,12 +27,23 @@ impl FiberResources {
...
-fn fiber_geometry(fibers: Reader) -> (Vec<FiberVertex>, Vec<u32>) {
-    let (mut vertices, ranges) = fiber_vertices(fibers);
+pub fn batches(fibers: Reader, client: &Client) -> Vec<FiberBatch> {
+    let mut iter = fibers.into_streamlines_iter().peekable();
+    let mut batches = vec![];
+
+    while iter.peek().is_some() {
+        let streamlines = iter.by_ref().take(client.streamline_batch_size).collect();
+        batches.push(FiberBatch::new(streamlines, &client.device));
+    }
```
Comment (nilgoyette) [inline src/graphics/resources/fibers.rs]: I'm surprised but the way you wrote this loop. Can you please explain in your own words why you used the "peek" concept instead of a standard iteration?

File: src/graphics/pipeline.rs (hunk 2 above)
Comment (carlOSx64) [reply src/graphics/pipeline.rs]: Wow, I did not know that booleans had functions ! This is great, I'll use this.

File: src/graphics/resources/fibers.rs (hunk 3 above)
Comment (carlOSx64) [reply src/graphics/resources/fibers.rs]: There is probably room for improvement here. Here's how it works:

There are two iterations at play here, the first one goes on until the end and the other one retrieves a batch of streamlines (`.take(streamline_batch_size)`). Taking a batch mutates the iterator. A basic iterator can only be queried with `next()` which is why I used a peekable iterator, it allows us to look if the iterator is at the end without modifing it.

I'm not sure how I would be able to implement this logic with a regular iterator. Let me know if there's a better way or if my explanation is unclear.

File: src/graphics/resources/bind/group.rs (hunk 1 above)
Comment (carlOSx64) [reply src/graphics/resources/bind/group.rs:28]: Good to know! I'll take some notes on how to use a mask next time we meet. This could be easily implemented in the resampling shader.

File: src/graphics/resources/fibers.rs (hunk 3 above)
Comment (nilgoyette) [reply src/graphics/resources/fibers.rs]: Does something like [this](https://users.rust-lang.org/t/how-to-breakup-an-iterator-into-chunks/87915/5) solve your problem? Maybe it's uselessly complex. I'm not sure. I fell like there's a cost to use peekable, but I'm probably wrong.

Comment (carlOSx64) [reply src/graphics/resources/fibers.rs]: Yes, this works. This is basically `chunks(..)` but for an iterator instead of a `Vec`. I don't think the overhead is too bad, the iteration runs 26 times on the whole brain tracking using the default batch size.

Here's the new version:
```rust
pub fn batches(fibers: Reader, client: &Client) -> Vec<FiberBatch> {
    let mut iter = fibers.into_streamlines_iter();

    std::iter::from_fn(|| {
        let streamlines: Vec<Streamline> =
            iter.by_ref().take(client.streamline_batch_size).collect();

        (!streamlines.is_empty()).then(|| FiberBatch::new(streamlines, &client.device))
    })
    .collect()
}
```

**Comment by nilgoyette** [comment]
Sorry, I forgot about that MR.
